export const AuthApi = process.env.REACT_APP_AUTH_API || 'http://localhost:8080/'
export const BaseApi = process.env.REACT_APP_MASTER_API || 'http://localhost:8080'
export const BucketS3 = process.env.REACT_APP_S3_BUCKET || 'https://s3-us-west-2.amazonaws.com/myp-public'
export const XlsImportApi = process.env.REACT_APP_XLS_IMPORT_API || 'http://localhost:5199/v2'
export const ImportApi = process.env.REACT_APP_IMPORT_API || 'http://localhost:9000/'
