module.exports = {
  AboutUsSchema: require('./aboutUsSchema'),
  StoreSchema: require('./storeSchema'),
  CountrySchema: require('./countrySchema'),
  ProductControlSchema: require('./controlSchema'),
  CustomerSchema: require('./customerSchema'),
  CategorySchema: require('./categorySchema'),
  ManufacturerSchema: require('./manufacturerSchema'),
  ProductClassificationSchema: require('./classificationSchema'),
  ProductSchema: require('./product.model'),
  OrderSchema: require('./orderSchema'),
  StatusOrderSchema: require('./orderStatusSchema'),
  SettingSchema: require('./settingSchema'),
  FileSchema: require('./file.Schema'),
  PMCRegionSchema: require('./pmcRegions.model'),
  NeighborhoodSchema: require('./neighborHoodSchema'),
  StateSchema: require('./stateSchema'),
  CitySchema: require('./citySchema'),
  AddressSchema: require('./addressSchema'),
  DeliveryFeeSchema: require('./deliveryFeeSchema'),
  ProductSlugSchema: require('./productSlug.model'),
  PmcValueInRegionsSchema: require('./pmcValuesInRegionsSchema'),
  UserSchema: require('./userSchema'),
  ShowCaseSchema: require('./showCaseSchema'),
  SpecialProductSchema: require('./specialProductSchema')
}
