version: '3'

services:
  backoffice-api:
    image: ambientum/node:16
    container_name: backoffice-api
    command: bash -c "npm i && npm run dev"
    ports:
      - '${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}'
    volumes:
      - .:/var/www/app
