// Routing version
const name = 'v1'

// Routes for this version
const routes = {
  '/user': require('./user'),
  '/plan': require('./plan'),
  '/category': require('./category'),
  '/manufacturer': require('./manufacturer'),
  '/file': require('./file'),
  '/store': require('./store'),
  '/customer': require('./customer'),
  '/product': require('./product'),
  '/virtualProduct': require('./virtualProduct'),
  '/productClassification': require('./productClassification'),
  '/productControl': require('./productControl'),
  '/file': require('./file'),
  '/banner': require('./banner'),
  '/neighborhood': require('./neighborhood'),
  '/city': require('./city'),
  '/state': require('./state'),
  '/country': require('./country'),
  '/publicAddress': require('./publicAddress'),
  '/deliveryFee': require('./deliveryFee'),
  '/distanceDeliveryFee': require('./distanceDeliveryFee'),
  '/statusOrder': require('./StatusOrder'),
  '/order': require('./order'),
  '/orders': require('./orders'),
  '/historyOrder': require('./historyOrder'),
  '/openingHour': require('./openingHour'),
  '/aboutUs': require('./aboutUs'),
  '/historyAboutUs': require('./historyAboutUs'),
  '/statistcOrder': require('./statisticOrder'),
  '/statisticsCustomer': require('./statisticsCustomer'),
  '/lastOrdersPending': require('./lastOrderPending'),
  '/salesHistory': require('./salesHistory'),
  '/paymentMethods': require('./paymentMethod'),
  '/showcase': require('./showCase'),
  '/cupom': require('./cupom'),
  '/erp': require('./erp'),
  '/integrationsql': require('./integrationSQL'),
  '/ganalytics': require('./ganalytics'),
  '/storeLayout': require('./storeLayout'),
  '/deliverySchedule': require('./deliverySchedule'),
  '/storeDelivery': require('./storeDeliveries'),
  '/paymentOption': require('./paymentOption'),
  '/customer/statistics': require('./customerStatistics'),
  '/categories': require('./categories'),
  '/storeintegration': require('./storeIntegration'),
  '/products': require('./productPromotion'),
  '/billboard': require('./billboard'),
  '/stores/group': require('./storeGroup'),
  '/route/links': require('./routeLinks'),
  '/report': require('./report'),
  '/integration': require('./integration'),
  '/history': require('./importHistory'),
  '/marketing': require('./marketingAutomations'),
  '/integration/module': require('./module'),
  '/pbm': require('./pbm')
}

module.exports = {
  name,
  routes,
}
