// Export all models schemas
module.exports = {
  // Key pairs for jwt validation
  KeySchema: require('./key.model'),
  CategorySchema: require('./category.model'),
  ManufacturerSchema: require('./manufacturer.model'),
  UserSchema: require('./user.model'),
  PlanSchema: require('./plan.model'),
  StoreSchema: require('./store.model'),
  CustomerSchema: require('./customer.model'),
  ProductSchema: require('./product.model'),
  ProductControlSchema: require('./productControl.model'),
  ProductClassificationSchema: require('./productClassification.model'),
  BannerSchema: require('./banner.model'),
  NeighborhoodSchema: require('./neighborHood.model'),
  CitySchema: require('./city.model'),
  StateSchema: require('./state.model'),
  CountrySchema: require('./country.model'),
  DeliveryFeeSchema: require('./deliveryFee.model'),
  PublicAddressSchema: require('./publicAddress.model'),
  StatusOrderSchema: require('./statusOrder.model'),
  HistoryOrderSchema: require('./historyOrder.model'),
  OpeningHourSchema: require('./openingHour.model'),
  AboutUsSchema: require('./aboutUs.model'),
  HistoryAboutUsSchema: require('./historyAboutUs.model'),
  OrderSchema: require('./order.model'),
  PaymentMethodSchema: require('./paymentMethod.model'),
  ShowCaseSchema : require('./showcase.model'),
  CupomSchema : require('./cupom.model'),
  ERPSchema : require('./erp.model'),
  IntegrationSQLSchema : require('./integrationSql.model'),
  DeliveryScheduleSchema: require('./deliverySchedule.model'),
  PaymentOptionSchema: require('./paymentOptions.model'),
  StoreIntegrationSchema: require('./storeIntegration'),
  PMCSchema: require('./pmc.model'),
  FileSchema: require('./file.model'),
  ProductDescriptionSchema: require('./productDescription.model'),
  StoreGroupSchema: require('./storeGroup.model'),
  PasswordRecoverySchema: require('./passwordRecovery.model'),
}
