name: New Ecommerce Production Deploy
on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setting environment file
        run: |
          cp .env.prod .env
      - name: Install Dependencies
        run: |
          npm install --force
      - name: Production Build
        run: |
          npm run build
      - name: Deploy to AWS
        uses: InscribeAI/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_NEW_LAYOUT_PROD_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_NEW_LAYOUT_REGION }}
          AWS_CF_DISTRIBUTION_ID: ${{ secrets.AWS_CF_NEW_LAYOUT_PROD_DISTRIBUTION_ID }}
          REACT_APP_ELASTIC_ENV: production
          REACT_APP_ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
          REACT_APP_ELASTIC_ENDPOINT: ${{ secrets.ELASTIC_ENDPOINT }}
          SOURCE_DIR: "build"
