name: Backoffice Alpha Deploy
on:
  push:
    branches: 
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setting environment file
      run: |
        cp .env.dev .env
    - name: Install Dependencies
      run: |
        npm install
    - name: Alpha Build
      run: |
        npm run build
    - name: Deploy to AWS
      uses: InscribeAI/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_ALPHA_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_CF_DISTRIBUTION_ID: ${{ secrets.AWS_CF_ALPHA_DISTRIBUTION_ID }}
        REACT_APP_S3_BUCKET: ${{ secrets.REACT_APP_S3_BUCKET }}
        SOURCE_DIR: "build"
