name: Admin Auth API Production Deploy
on:
  push:
    branches:
      - production
jobs:
  docker:
    name: Deploy - Docker Hub
    runs-on: ubuntu-22.04
    env:
      REPO: ${{ secrets.DOCKER_PROD_REPO }}
    steps:
      - uses: actions/checkout@v1

      - name: Create production environment
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASE_ENV: production
          envkey_DATABASE_HOST: ${{ secrets.PROD_MONGO_HOST }}
          envkey_DATABASE_NAME: ${{ secrets.PROD_MONGO_NAME }}
          envkey_DATABASE_USERNAME: ${{ secrets.PROD_MONGO_USERNAME }}
          envkey_DATABASE_PASSWORD: ${{ secrets.PROD_MONGO_PASSWORD }}
          envkey_JWT_ISSUER: ${{ secrets.PROD_JWT_ISSUER }}
          envkey_JWT_SUBJECT: ${{ secrets.PROD_JWT_SUBJECT }}
          envkey_JWT_AUDIENCE: ${{ secrets.PROD_JWT_AUDIENCE }}
          envkey_JWT_EXPIRES: ${{ secrets.PROD_JWT_EXPIRES }}
          envkey_JWT_ALGORITHM: ${{ secrets.PROD_JWT_ALGORITHM }}
          envkey_SENDGRID_API_KEY: ${{ secrets.PROD_SENDGRID_API_KEY }}
          envkey_SENDGRID_EMAIL_SENDER: ${{ secrets.PROD_SENDGRID_EMAIL_SENDER }}
          envkey_FACEBOOK_SECRET: ${{ secrets.PROD_FACEBOOK_SECRET }}
          envkey_FACEBOOK_BASE_URL: ${{ secrets.FACEBOOK_BASE_URL }}
          envkey_FACEBOOK_CLIENT_ID: ${{ secrets.PROD_FACEBOOK_CLIENT_ID }}
          envkey_FACEBOOK_LOGIN_URL: ${{ secrets.FACEBOOK_LOGIN_URL }}
          envkey_GOOGLE_SECRET: ${{ secrets.PROD_GOOGLE_SECRET }}
          envkey_GOOGLE_CLIENT_ID: ${{ secrets.PROD_GOOGLE_CLIENT_ID }}
          envkey_GOOGLE_LOGIN_URL: ${{ secrets.GOOGLE_LOGIN_URL }}
          envkey_GOOGLE_GET_PROFILE: ${{ secrets.GOOGLE_GET_PROFILE }}
          envkey_REDIS_HOST: ${{ secrets.REDIS_HOST }}
          envkey_REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          envkey_REDIS_PORT: ${{secrets.REDIS_PORT }}
          envkey_NEW_ADMIN_URL: ${{ secrets.PROD_NEW_ADMIN_URL }}
          envkey_SHIPPING_API: ${{ secrets.DEV_SHIPPING_API }}
          envkey_AUTH_REDIRECT: ${{ secrets.AUTH_REDIRECT }}

          envkey_NODE_ENV: production
          file_name: .env

      - name: Installing Dependencies
        run: npm install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Running Tests
        run: npm run test

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker Image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker Image
        run: docker push $REPO
