export default interface StoreSettings {
    config_cnpj?: string
    config_phone?: string
    config_cpf_checkout?: boolean
    config_hide_prices?: boolean
    config_store_city?: string
    config_store_number?: string
    config_pharmacist_crf?: string
    config_pharmacist_name?: string
    config_responsible_name?: string
    config_email?: string
    config_google_tag_manager_id?: string
    config_color?: string
    config_stock?: boolean
    config_show_celphone?: boolean
    config_navbar_color?: string
    config_meta_keyword?: string
    config_meta_description?: string
    config_meta_title?: string
    config_cep?: string
    config_hotjar_id?: string
    config_owner?: string
    config_address?: string
    config_schema_markup?: string
    config_navbar_text_color?: object
    config_whatsapp_button?: boolean
    config_withdraw?: boolean
    config_whatsapp_phone?: string
    config_tawk_embed?: string
    config_url?: string
    config_name?: string
    config_company_name?: boolean
    config_analytics_id?: string
    config_analytics_api_client_id?: boolean
    config_logo?: {
        name: string
        folder: string
        url: string
        key: string
    }
    config_ssl?: string
    config_eurofarma_partner?: boolean
    config_pixel_id?: string
    config_special_price?: boolean
    config_discount_mypharma_covenant?: boolean
    config_max_discount?: boolean
    gaview?: string
    ga_client_email?: string
    ga_private_key?: string
    config_facebook_appId?: string
    config_facebook_secretKey?: string
    config_google_clientId?: string
    config_google_secretkey?: string
    config_cx_email?: string
    config_cx_id?: string
    config_ifood_store_id?: string
    config_ifood_client_id?: string
    config_ifood_client_secret?: string
    config_ifood_charge_percentage?: number
    config_ifood_charge_active?: boolean
    config_new_layout?: boolean
    config_always_show_popup?: boolean
}
