export default () =>
  ({
    labelBox: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      gap: '10px',
      padding: '15px 0',
    },
    boxQuantity: {
      backgroundColor: '#fff',
      borderRadius: '20px',
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '5px',
      minWidth: '120px',
      minHeight: '40px',
      maxHeight: '40px',
      padding: '0 10px',
    },
    buttonQuantity: {
      fontWeight: 'bold',
      fontSize: '15px',
      padding: '5px px',
      maxWidth: '30px',
      minWidth: '30px',
      maxHeight: '30px',
      minHeight: '30px',
    },
    boxPrice: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '5px',
      backgroundColor: '#fff',
      borderRadius: '20px',
      textAlign: 'center',
      maxHeight: '40px',
      minHeight: '40px',
      minWidth: '140px',
      padding: '0 10px',
    },
    price: {
      fontSize: '13px !important',
    },
    buttonEditPrice: {
      minWidth: '40px',
      maxWidth: '40px',
      minHeight: '40px',
      maxheight: '40px',
      padding: '0 !important',
    },
    infoBox: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    },
    subtitle: {
      fontSize: '12px',
    },
  } as any)
