version: '3'

services:
  ifood-api-integration:
    image: ambientum/node:16
    container_name: ifood-api-integration
    command: bash -c "npm i && npm run dev"
    volumes:
      - .:/var/www/app
