const Sequelize = require('sequelize');

const Order = {
    order_id: {type: Sequelize.INTEGER(11), autoIncrement: true, primaryKey: true},
    invoice_no: {type: Sequelize.INTEGER(11), defaultValue: 0},
    invoice_prefix: Sequelize.STRING(26),
    store_id: Sequelize.INTEGER(11),
    store_name: Sequelize.STRING(64),
    store_url: Sequelize.STRING(255),
    customer_id: Sequelize.INTEGER(11),
    customer_group_id: Sequelize.INTEGER(11),
    firstname: Sequelize.STRING(32),
    lastname: Sequelize.STRING(32),
    email: Sequelize.STRING(96),
    cpf: Sequelize.STRING(255),
    telephone: Sequelize.STRING(32),
    fax: Sequelize.STRING(32),
    custom_field: Sequelize.TEXT,
    payment_firstname: Sequelize.STRING(32),
    payment_lastname: Sequelize.STRING(32),
    payment_company: Sequelize.STRING(60),
    payment_address_1: Sequelize.STRING(128),
    payment_address_2: Sequelize.STRING(128),
    payment_city: Sequelize.STRING(128),
    payment_postcode: Sequelize.STRING(10),
    payment_country: Sequelize.STRING(128),
    payment_country_id: Sequelize.INTEGER(11),
    payment_zone: Sequelize.STRING(128),
    payment_zone_id: Sequelize.INTEGER(11),
    payment_address_format: Sequelize.TEXT,
    payment_custom_field: Sequelize.TEXT,
    payment_method: Sequelize.STRING(128),
    payment_code: Sequelize.STRING(128),
    shipping_firstname: Sequelize.STRING(32),
    shipping_lastname: Sequelize.STRING(32),
    shipping_company: Sequelize.STRING(60),
    shipping_address_1: Sequelize.STRING(128),
    shipping_address_2: Sequelize.STRING(128),
    shipping_city: Sequelize.STRING(128),
    shipping_postcode: Sequelize.STRING(10),
    shipping_country: Sequelize.STRING(128),
    shipping_country_id: Sequelize.INTEGER(11),
    shipping_zone: Sequelize.STRING(128),
    shipping_zone_id: Sequelize.INTEGER(11),
    shipping_address_format: Sequelize.TEXT,
    shipping_custom_field: Sequelize.TEXT,
    shipping_method: Sequelize.STRING(128),
    shipping_code: Sequelize.STRING(128),
    comment: Sequelize.TEXT,
    total: Sequelize.DECIMAL(15, 4),
    order_status_id: Sequelize.INTEGER(11),
    affiliate_id: Sequelize.INTEGER(11),
    commission: Sequelize.DECIMAL(15, 4),
    marketing_id: Sequelize.INTEGER(11),
    tracking: Sequelize.STRING(64),
    language_id: Sequelize.INTEGER(11),
    currency_id: Sequelize.INTEGER(11),
    currency_code: Sequelize.STRING(3),
    currency_value: {type: Sequelize.DECIMAL(15, 8), defaultValue: 1.00000000},
    ip: Sequelize.STRING(40),
    forwarded_ip: Sequelize.STRING(40),
    user_agent: Sequelize.TEXT,
    accept_language: Sequelize.STRING(255),
    date_added: Sequelize.DATE,
    date_modified: Sequelize.DATE
}

module.exports = Order;
